#!/usr/bin/env node
/**
 * Fetches recent posts from Jay's blog (jayambadkar.github.io) at build time and
 * writes them to src/data/posts.ts as typed data.
 *
 * Never fails the build: if the feed can't be fetched or parsed, the committed
 * src/data/posts.ts is left untouched and a warning is printed.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const BLOG_URL = 'https://jayambadkar.github.io';
const FEED_URL = `${BLOG_URL}/feed.xml`;
const OUT = fileURLToPath(new URL('../src/data/posts.ts', import.meta.url));
const MAX_EXCERPT = 180;

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'", nbsp: ' ' };

function decode(text) {
  return text
    .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
    .replace(/&#x([0-9a-f]+);/gi, (_, h) => String.fromCodePoint(parseInt(h, 16)))
    .replace(/&#(\d+);/g, (_, d) => String.fromCodePoint(Number(d)))
    .replace(/&([a-z]+);/gi, (m, n) => ENTITIES[n.toLowerCase()] ?? m);
}

function clean(html) {
  let text = decode(html)
    .replace(/<[^>]+>/g, ' ')
    // Drop footnote markers and the footnote text that Jekyll appends to excerpts.
    .replace(/\(see \d+\)[\s\S]*$/, '')
    .replace(/↩/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (text.length > MAX_EXCERPT) {
    text = `${text.slice(0, MAX_EXCERPT).replace(/\s+\S*$/, '')}…`;
  }
  return text;
}

function pick(entry, re) {
  const m = entry.match(re);
  return m ? m[1] : undefined;
}

function parse(xml) {
  const entries = xml.match(/<entry>[\s\S]*?<\/entry>/g) ?? [];
  return entries
    .map((e) => {
      const title = pick(e, /<title[^>]*>([\s\S]*?)<\/title>/);
      const href = pick(e, /<link[^>]*href="([^"]+)"/);
      const published = pick(e, /<published>([^<]+)<\/published>/);
      if (!title || !href || !published) return undefined;
      const url = new URL(href, BLOG_URL).toString();
      return {
        title: clean(title),
        date: published.slice(0, 10),
        url,
        categories: [...e.matchAll(/<category term="([^"]+)"/g)].map((m) => decode(m[1])),
        excerpt: clean(pick(e, /<summary[^>]*>([\s\S]*?)<\/summary>/) ?? ''),
      };
    })
    .filter(Boolean)
    .sort((a, b) => b.date.localeCompare(a.date));
}

async function main() {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 10_000);
  try {
    const res = await fetch(FEED_URL, { signal: controller.signal });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const posts = parse(await res.text());
    if (posts.length === 0) throw new Error('no posts found in feed');

    const body = `// AUTO-GENERATED by scripts/fetch-posts.mjs from ${FEED_URL}.
// Do not edit by hand; run \`npm run fetch:posts\` (also runs before every build).
import type { Post } from './types';

export const BLOG_URL = ${JSON.stringify(BLOG_URL)};

export const posts: readonly Post[] = ${JSON.stringify(posts, null, 2)};
`;
    await writeFile(OUT, body);
    console.log(`fetch-posts: wrote ${posts.length} posts to src/data/posts.ts`);
  } catch (err) {
    console.warn(
      `fetch-posts: could not refresh posts (${err instanceof Error ? err.message : String(err)}); keeping committed src/data/posts.ts`,
    );
  } finally {
    clearTimeout(timer);
  }
}

await main();
