// AUTO-GENERATED by scripts/fetch-posts.mjs from https://jayambadkar.github.io/feed.xml.
// Do not edit by hand; run `npm run fetch:posts` (also runs before every build).
import type { Post } from './types';

export const BLOG_URL = "https://jayambadkar.github.io";

export const posts: readonly Post[] = [
  {
    "title": "NEW POST!!!",
    "date": "2026-05-16",
    "url": "https://jayambadkar.github.io/life/uni/2026/05/16/new-post.html",
    "categories": [
      "life",
      "uni"
    ],
    "excerpt": "IT’S BEEN SO LONG! HIII…"
  },
  {
    "title": "Post exam feels",
    "date": "2025-01-15",
    "url": "https://jayambadkar.github.io/exams/life/2025/01/15/post-exam-highs.html",
    "categories": [
      "exams",
      "life"
    ],
    "excerpt": "Now that those pesky exams are past me, let me do a lil bit of a recap, almost like a “wrapped”, but probably worse…"
  },
  {
    "title": "Oh my days",
    "date": "2025-01-15",
    "url": "https://jayambadkar.github.io/life/uni/2025/01/15/oh-my-days.html",
    "categories": [
      "life",
      "uni"
    ],
    "excerpt": "Keep learning! Starting with “a b c d z f…” (in retrospect, that sells this post really badly)"
  },
  {
    "title": "Happy New Year!",
    "date": "2025-01-04",
    "url": "https://jayambadkar.github.io/life/2025/01/04/new-year.html",
    "categories": [
      "life"
    ],
    "excerpt": "Happy new year y’all and sorry about the recent lack of posting…"
  },
  {
    "title": "New to uni… new life…",
    "date": "2024-10-11",
    "url": "https://jayambadkar.github.io/maths/life/2024/10/11/new-uni-life.html",
    "categories": [
      "maths",
      "life"
    ],
    "excerpt": "Settling into the UK and Europe’s #1 university for a pretty fun course…"
  },
  {
    "title": "STEP / TMUA advice",
    "date": "2024-08-29",
    "url": "https://jayambadkar.github.io/maths/2024/08/29/step-advice.html",
    "categories": [
      "maths"
    ],
    "excerpt": "I’ve made this page as I’ve got a few requests for advice so far, and it’s just easier for everyone if I send them to a website that I can keep centrally updated."
  },
  {
    "title": "A few new things… (pt. 2)",
    "date": "2024-08-25",
    "url": "https://jayambadkar.github.io/life/2024/08/25/a-few-new-things-2.html",
    "categories": [
      "life"
    ],
    "excerpt": "Another while since my last post, so I thought an update on my brilliant(ly boring) life might be due."
  },
  {
    "title": "Beloved old essays",
    "date": "2024-08-22",
    "url": "https://jayambadkar.github.io/maths/2024/08/22/big-essay.html",
    "categories": [
      "maths"
    ],
    "excerpt": "In an unusually serious and thought-about post, I introduce some of the long research-based thinking that I’ve done over the last few years and reflect a little (I’ll try to not…"
  },
  {
    "title": "It’s over (2024 exam season)",
    "date": "2024-06-25",
    "url": "https://jayambadkar.github.io/exams/2024/06/25/exams-wk-5.html",
    "categories": [
      "exams"
    ],
    "excerpt": "It’s over :("
  },
  {
    "title": "A levels!!!! (wk. 4)",
    "date": "2024-06-22",
    "url": "https://jayambadkar.github.io/exams/2024/06/22/exams-wk-4.html",
    "categories": [
      "exams"
    ],
    "excerpt": "Mwah ha ha…"
  }
];
